### PR TITLE
Controller Exception Handling

### PR DESCRIPTION
**Pull request by twinhooker**
rethrows on error. So you should handle error responses by your self

### CODE REVIEW

**Comment by twinhooker** [comment]
If some one wants to handle exceptions from controllers he can now override
Kelp::Response::render_500.

**Comment by twinhooker** [comment]
I finally returned back to our web interfaces. Sorry for long delay (;

**Comment by naturalist** [comment]
Did you find a different solution? I was inclined to add your fix to the code base.

**Comment by twinhooker** [comment]
Hello.
Please excuse me for mess in the pull requests. I strugled one more bug and then realized that I've sent pull request from master branch. So I closed it.

Better solution is to stringify exception not in the controller but in Kelp::Response::render_500. So if some one decides to handle exceptions different way(not strigifying it) he could just create own Response object with method render_500 that handles it.

If I find some time today or tomorrow I will recreate this pull request and create one more (: 

And congratulations to you and me (: We use your framework now in production. 

With best regards,
Konstantin Yakunin

**Pull request closed without merging**
